[package]
name = "dilemma"
version = "0.1.0"
edition = "2021"
description = "A tournament organiser for the iterated prisoner's dilemma"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
